### ISSUE TITLE
Exception in thread Thread-1:

### ISSUE THREAD

**Issue by Bhanukavimukthi** [adujardin/chainer-pose-proposal-net#2]
Its run fine with 'python high_speed.py result/resnet18_384x384_coco/'. But when its run 'python high_speed_zed.py result/resnet18_384x384_coco/'  it keeps giving this error

(zedpose) C:\Users\Bhanuka Madurawala\Desktop\zed-pose-proposal-net-master> python high_speed_zed.py result/resnet18_384x384_coco/
INFO:OpenGL.acceleratesupport:OpenGL_accelerate module loaded
INFO:OpenGL.arrays.arraydatatype:Using accelerated ArrayDatatype
INFO:OpenGL.GLUT.special:Using NT-specific GLUT calls with exit callbacks
INFO:predict:result/resnet18_384x384_coco/src\config.ini
INFO:predict:cuda enable True
INFO:predict:ideep enable False
INFO:predict:gpu mode
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\zedpose\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\zedpose\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "high_speed_zed.py", line 105, in high_speed
    init_cap_params.camera_resolution = sl.RESOLUTION.RESOLUTION_HD720
  File "C:\ProgramData\Anaconda3\envs\zedpose\lib\enum.py", line 349, in __getattr__
    raise AttributeError(name) from None

I'm using windows 10
python 3.7
CUDA 10.2
Nvidia GTX 950

**Comment by adujardin** [comment]
Which version of the ZED SDK are you using? This code was developed for ZED SDK 2.X, the current version is 3.1 and the API changed.

You should either downgrade to ZED SDK 2.8 and the compatible Python API that goes with it or update this code for the 3.0 API.

In that specific case upgrading the API to 3.0 gives : 
```py
init_cap_params.camera_resolution = sl.RESOLUTION.HD720
```

**Comment by Bhanukavimukthi** [comment]
Thank you very much for your support Yeah i think thats the problem. I'm using zed sdk 3.1
and this error overcome and got another problem here

(highspeedzed) C:\Users\Bhanuka Madurawala\Desktop\zed-pose-proposal-net-master> python high_speed_zed.py result/resnet18_384x384_coco/
INFO:OpenGL.acceleratesupport:OpenGL_accelerate module loaded
INFO:OpenGL.arrays.arraydatatype:Using accelerated ArrayDatatype
INFO:OpenGL.GLUT.special:Using NT-specific GLUT calls with exit callbacks
INFO:predict:result/resnet18_384x384_coco/src\config.ini
INFO:predict:cuda enable True
INFO:predict:ideep enable False
INFO:predict:gpu mode
Opening ZED Camera...
Exception in thread Capture:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\highspeedzed\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "high_speed_zed.py", line 47, in run
    self.cap.retrieve_image(left, sl.VIEW.LEFT,  width=self.insize[0], height=self.insize[1])
  File "pyzed\sl.pyx", line 5644, in pyzed.sl.Camera.retrieve_image
TypeError: retrieve_image() got an unexpected keyword argument 'width'

**Comment by adujardin** [comment]
`retrieve_image` now takes a resolution and no longer width + height, see [API doc](https://www.stereolabs.com/docs/api/python/classpyzed_1_1sl_1_1Camera.html#a81c0b6777dfbdf39795b500ead89a358)

This should be something like :
```py
self.cap.retrieve_image(left, sl.VIEW.LEFT, resolution=sl.Resolution(self.insize[0], self.insize[1]))
```

**Comment by Bhanukavimukthi** [comment]
Thank you very much. Highly appreciate
